# Generated by Django 3.2 on 2021-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
