# Generated by Django 3.2 on 2021-05-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_ad_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Комедия'), (2, 'Ужасы'), (3, 'Боевик'), (4, 'Триллер'), (5, 'Приключение'), (6, 'Драма'), (7, 'Мелодрама'), (8, 'Детектив'), (9, 'Фантастика'), (10, 'Фентези')]),
        ),
    ]
