# Generated by Django 3.2 on 2021-05-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcinema',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cafebar',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='childroom',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='viphall',
            name='description',
            field=models.TextField(),
        ),
    ]
