# Generated by Django 3.2 on 2021-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20210510_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='phone_color',
            field=models.BooleanField(default=0),
        ),
    ]
